---
name: Setup and build

on:
  
  workflow_dispatch:

env:
  LOCAL_ANSIBLE_DIR: ansible-local
  TARBALL_LOCATION: collection-tarballs

jobs:
  # setup:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 2

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.12
  #         cache: 'pip'

  #     - name: Install yamllint
  #       run: pip install -r requirements.txt

        
  release:
    runs-on: ubuntu-latest
    # needs: setup
    steps:
      - name : download ansible collection
        uses: actions/download-artifact@v3
        with:
          name: ansible-collection
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: First-Release
          files: ansible-collection.gz
          
      
