name: create and modify an array
on: workflow_dispatch

env: 
   environments: S1,S2
   #python_output: (S1 S2 S3 S4)


   


jobs:
  traverse-an-array:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: loop through an array
        id: step1
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: |
           #output=$(python test_array.py "$environments")
           echo $(python test_array.py "$environments") >> ${GITHUB_OUTPUT}
           #python test_array.py "$environments"
           # echo "::set-output name=python-list::$output"
           # echo $output
        
      - name: Print changelog
        run: echo "${{ steps.step1.outputs.OUTPUT_LIST }}"
