---
name: download release

on:
  
  workflow_dispatch:

env:
  LOCAL_ANSIBLE_DIR: ansible-local
  TARBALL_LOCATION: collection-tarballs

jobs:
  # setup:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 2

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.12
  #         cache: 'pip'

  #     - name: Install yamllint
  #       run: pip install -r requirements.txt

        
  download-release:
    runs-on: ubuntu-latest
    # needs: setup
    steps:
       - name: download
         uses: pozetroninc/github-action-get-latest-release@master
         with:
          repository: rathi-payal1992/Ansible-Code
          
      
