---
name: Setup and build

on:
  push:
  workflow_call:

env:
  LOCAL_ANSIBLE_DIR: ansible-local
  TARBALL_LOCATION: collection-tarballs

jobs:
  # setup:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 2

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.12
  #         cache: 'pip'

  #     - name: Install yamllint
  #       run: pip install -r requirements.txt

        
  build:
    runs-on: ubuntu-latest
    # needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Build Ansible collection
        run: |
          pwd
          git branch
          ansible-playbook test_ansible.yml
