name: test condition

on: 
  workflow_dispatch:
    inputs:
      Configure:
        description: 'Define env name'     
        required: true
        default: S1
    
jobs:
  job-s2:
    if: ${{ inputs.Configure}} == 'S2' 
    runs-on: ubuntu-latest
    steps:
     
       - run: echo "Running S2 ${{ inputs.Configure}}"
  job-s1:
    if: ${{ inputs.Confgiure}} == 'S1' 
    runs-on: ubuntu-latest
    steps:
     
       - run: echo "Running S1 ${{ inputs.Configure}}"
