name: test condition

on: 
  workflow_dispatch:
    inputs:
      Configure:
        description: 'Define env name'     
        required: true
        default: S1
    
jobs:
  job-s2:
    if: ${{ inputs.Confgure}} == 'S2' 
    runs-on: ubuntu-latest
    steps:
     
       - run: echo "Running S2"
  job-s1:
    if: ${{ inputs.Confgure}} == 'S1' 
    runs-on: ubuntu-latest
    steps:
     
       - run: echo "Running S1"
