name: build image
 
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - name: docker build and Push
        if: steps.image-cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: "alpine:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
 
      - name: docker load
        if: steps.image-cache.outputs.cache-hit == 'true'
        run: docker load -i ACTIONS_CACHE_URL/alpine:latest
 
  test:
      runs-on: ACTIONS_CACHE_URL/alpine:latest
      steps:      
        -name: list folders
         run:  ls -ltr
        
