name: use image
 
on:
  workflow_dispatch:
jobs:
  use:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: update_image.yml
          name: myimage
          
      

          
      
      - name: Load Docker image
        run: |
          docker load --input myimage.tar
          docker image ls -a
      - name: Run container using this image
        uses: addnab/docker-run-action@v3
        with:
          image: myimage:latest
          run: ls -ltr   
