name: use image
 
on:
  workflow_dispatch:
jobs:
  use:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Download artifact
      - uses: actions/download-artifact@v3
        with:
          name: myimage-${{ github.sha }}
      
      - name: Load Docker image
        run: |
          docker load --input myimage.tar
          docker image ls -a
          docker container run -d --name ansible myimage:latest
          docker exec -it ansible /bin/bash
          ansible-playbook 
